openapi: 3.0.0
servers:
  - url: /v1
info:
  description: >-
    This is the FAST REST API. It can be used to query or perturb the state of a
    running application.
  version: 1.0.0
  title: FAST

paths:

  # Part of the LL API
  /alive:
    get:
      description: Query the liveliness of the application.
      responses:
        '200':
          description: The application is alive.
        '503':
          description: The application is not alive.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  # Part of the LL API
  /process:
    post:
      description: Process a number of inputs.
      responses:
        '200':
          description: Work order accepted.
        '406':
          description: Work order not accepted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkOrder'

  # Part of the LL API
  /perturb:
    post:
      description: Modify scenario knobs.
      responses:
        '200':
          description: Perturbation successful.
        '406':
          description: Perturbation unsuccessful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Perturbation'

  # Part of the LL API
  /query:
    get:
      description: Query the current internal state of the application.
      responses:
        '200':
          description: Current internal state of the application.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        '406':
          description: Application execution mode change unsuccessful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /enable:
    post:
      description: Enable or disable adaptation.
      responses:
        '200':
          description: Application execution mode change successful.
        '406':
          description: Application execution mode change unsuccessful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationExecutionMode'

  /terminate:
    post:
      description: Terminate the application.
      responses:
        '200':
          description: The application termination request was received.

components:

  schemas:

    Error:
      type: object
      required:
        - id
        - description
      properties:
        id:
          type: integer
        description:
          type: string

    WorkOrder:
      type: object
      required:
        - inputs
      properties:
        inputs:
          type: integer
          minimum: 1

    Perturbation:
      type: object
      properties:
        missionIntent:
          $ref: '#/components/schemas/IntentSpecification'
        availableCores:
          description: Number of CPU cores on which the application is running.
          type: integer
          enum:
            - 2
            - 4
        availableCoreFrequency:
          description: Operating frequency of the CPU on which the application is running.
          type: integer
          enum:
            - 600
            - 1200
        missionLength:
          description: >-
            Mission length in iterations.
          type: integer
          minimum: 0

    ApplicationExecutionMode:
      type: object
      properties:
        adaptive:
          description: >-
            When true, the system will adapt with respect to the active intent.
            Otherwise execution will proceed without adaptation.
          type: boolean

    ExecutionMode:
      type: object
      required:
        - type
        - value
      properties:
        type:
          enum:
            - FAST.ExecutionMode
        value:
          enum:
            - Default
            - Emulated

    ResourceUsagePolicy:
      type: object
      required:
        - type
        - value
      properties:
        type:
          enum:
            - FAST.ResourceUsagePolicy
        value:
          enum:
            - Simple
            - Maintain
            - Maximal

    ActuationPolicy:
      type: object
      required:
        - type
        - value
      properties:
        type:
          enum:
            - FAST.ActuationPolicy
        value:
          enum:
            - Actuate
            - NoActuation

    InteractionMode:
      type: object
      required:
        - type
        - value
      properties:
        type:
          enum:
            - FAST.InteractionMode
        value:
          enum:
            - Default
            - Scripted

    IntentSpecificationString:
      description: A string containing FAST Intent Specification Language source code.
      type: string

    #### Begin JSON FAST ISL Intent Types ###

    IntentSpecification:
      description: >-
        JSON Representation of a FAST Intent Specification Language (ISL) source file.
      type: object
      required:
        - knobs
        - measures
        - intent
      properties:
        knobs:
          type: array
          items:
            $ref: '#/components/schemas/KnobDeclaration'
        measures:
          type: array
          items:
            $ref: '#/components/schemas/MeasureDeclaration'
        intent:
          type: object
          required:
            - name
            - optimizationType
            - objectiveFunction
            - constraints
          properties:
            name:
              type: string
            optimizationType:
              enum:
                - min
                - max
            objectiveFunction:
              description: >-
                An arithmetic expression over the measures declared in the measures
                parameter of the enclosing IntentSpecification.
              $ref: '#/components/schemas/Expression'
            constraint:
              $ref: '#/components/schemas/Predicate'
            constraintValue:
              type: number

    KnobDeclaration:
      type: object
      required:
        - name
        - range
        - referenceValue
      properties:
        name:
          type: string
        range:
          type: array
          items:
            type: number
        referenceValue:
          type: number

    MeasureDeclaration:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          
    Expression:
      type: object
      required:
        - expression
      properties:
        expression: 
          oneOf:
            - $ref: '#/components/schemas/ExpressionLiteral'
            - $ref: '#/components/schemas/ExpressionVariableName'
            - $ref: '#/components/schemas/ExpressionUnaryOperator'
            - $ref: '#/components/schemas/ExpressionBinaryOperator'
    
    ExpressionLiteral:
      type: object
      required:
        - literal
      properties:
        literal:
          type: number

    ExpressionVariableName:
      type: object
      required:
        - variableName
      properties:
        variableName:
          type: string

    ExpressionUnaryOperator:
      type: object
      required:
        - operator
        - expression
      properties:
        operator:
          enum:
            - '-'
        expression:
          $ref: '#/components/schemas/Expression'

    ExpressionBinaryOperator:
      type: object
      required:
        - operator
        - leftExpression
        - rightExpression
      properties:
        operator:
          enum:
            - '+'
            - '-'
            - '*'
            - '/'
        leftExpression:
          $ref: '#/components/schemas/Expression'
        rightExpression:
          $ref: '#/components/schemas/Expression'

    Predicate:
      type: object
      required:
        - predicate
      properties:
        predicate: 
          oneOf:
            - $ref: '#/components/schemas/PredicateBinaryRelation'
            - $ref: '#/components/schemas/PredicateBinaryOperator'

    PredicateBinaryRelation:
      type: object
      required:
        - operator
        - leftExpression
        - rightExpression
      properties:
        operator:
          enum:
            - '=='
            - '<='
            - '>='
        leftExpression:
          $ref: '#/components/schemas/Expression'
        rightExpression:
          $ref: '#/components/schemas/Expression'

    PredicateBinaryOperator:
      type: object
      required:
        - operator
        - leftPredicate
        - rightPredicate
      properties:
        operator:
          enum:
            - 'and'
        leftPredicate:
          $ref: '#/components/schemas/Predicate'
        rightPredicate:
          $ref: '#/components/schemas/Predicate'

    #### End JSON FAST ISL Intent Types ###

    NameValuePair:
      type: object
      description: Data representing the value of a knob or measure.
      required:
        - name
        - value
      properties:
        name:
          type: string
        value:
          type: number

    NameValuesPair:
      type: object
      description: Data representing the a named array of named values.
      required:
        - name
        - values
      properties:
        name:
          type: string
        values:
          type: array
          items: 
            $ref: '#/components/schemas/NameValuePair'
    
    NameValueAndRangePair:
      type: object
      description: Data representing the value and range of a knob .
      required:
        - name
        - value
      properties:
        name:
          type: string
        value:
          type: number
        range:
          type: array
          items:
            type: number
    
    # Identical to the response type of TH/status
    Status:
      type: object
      description: Data representing the current state of the SUT.
      required:
        - time
        - arguments
      properties:
        time:
          type: string
          description: UTC Time in RFC-3339 format.
        arguments:
          type: object
          description: >-
            The challenge application state, the system state, the scenario
            knobs, and the verdict components.
          required:
            - application
            - applicationKnobs
            - architecture
            - systemConfigurationKnobs
            - scenarioKnobs
            - measures
          properties:
            application:
              enum:
                - radar
                - x264
                - capsule
              description: Name of challenge problem application.
            applicationKnobs:
              type: array
              description: >-
                Application-dependent listing the value of each application knob.
              items:
                $ref: '#/components/schemas/NameValueAndRangePair'
            architecture:
              type: string
              description: Name of the system architecture.
            systemConfigurationKnobs:
              type: array
              description: >-
                Architecture dependent listing the value of each system
                configuration knob.
              items:
                $ref: '#/components/schemas/NameValueAndRangePair'
            scenarioKnobs:
              type: array
              description: >-
                Architecture dependent settings describing the current available
                system resources such as the number of cores and maximal
                operation frequency.
              items:
                $ref: '#/components/schemas/NameValuePair'
            measures:
              type: array
              description: Values of measures specified in the intent specification.
              items:
                $ref: '#/components/schemas/NameValuePair'
            measurePredictions:
              type: array
              description: Values of measures specified in the intent specification as predicted by the active controller model.
              items:
                $ref: '#/components/schemas/NameValuePair'
            verdictComponents:
              type: array
              description: The verdict components of the active intent specifications.
              items:
                $ref: '#/components/schemas/NameValuesPair'