swagger: "2.0"
info:
  description: "This is the FAST REST API. It can be used to query or perturb the state of a running application."
  version: "1.0.0"
  title: "FAST"
basePath: "/v1"
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /alive:
    get:
      description: "Query the liveliness of the application."
      produces: 
        - application/json
      responses:
        "200":
          description: "The application is alive."
        "503":
          description: "The application is not alive."
          schema:
            $ref: '#/definitions/Error'
  /process:
    post:
      description: "Process a number of inputs."
      parameters: 
        - in: body
          name: workOrder
          schema: 
            $ref: '#/definitions/WorkOrder'
      responses:
        200:
          description: "Work order accepted."
        406:
          description: "Work order not accepted."
          schema: 
            $ref: '#/definitions/Error'
  /perturb:
    post:
      description: "Modify scenario knobs."
      parameters: 
        - in: body
          name: perturbation
          schema: 
            $ref: '#/definitions/Perturbation'
      responses:
        200:
          description: "Perturbation successful."
        406:
          description: "Perturbation unsuccessful."
          schema: 
            $ref: '#/definitions/Error'
  /query:
    get:
      description: "Query the current internal state of the application."
      responses:
        200:
          description: "Current internal state of the application."
  /enable:
    post:
      description: "Enable or disable adaptation."
      parameters: 
        - in: body
          name: applicationExecutionMode
          schema: 
            $ref: '#/definitions/ApplicationExecutionMode'
      responses:
        200:
          description: "Application execution mode change successful."
        406:
          description: "Application execution mode change unsuccessful."
          schema: 
            $ref: '#/definitions/Error'
  /terminate:
    post:
      description: "Terminate the application."
      responses:
        "200":
          description: "The application termination request was received."
  
definitions:

  Error:
    type: object
    required: 
      - id
      - description
    properties:
      id:
        type: integer
      description:
        type: string

  WorkOrder:
    type: object
    required:
      - inputs
    properties:
      inputs: 
        type: integer
        minimum: 1
  
  Perturbation:
    type: object
    properties:
      missionIntent:
        description: "Intent expressed in the FAST Intent Specification Langauge."
        type: string
      availableCores:
        description: "Number of CPU cores on which the application is running."
        type: integer
        enum: [1, 2, 3, 4]
      availableCoreFrequency:
        description: "Operating frequency of the CPU on which the application is running."
        type: integer
        enum: [300, 400, 600, 1200]
      missionLength:
        description: "Mission length in minutes. Affects the maximum permitted energy usage."
        type: integer
        minimum: 0
        maximum: 1000
      sceneObfuscation:
        description: "Amount of additive noise applied to input. Used to model conditions such as fog that affect how informative the input signal is."
        type: number
        minimum: 0
        maximum: 1

  ApplicationExecutionMode:
    type: object
    properties:
      adaptive:
        description: "When true, the system will adapt with respect to the active intent. Otherwise execution will proceed without adaptation."
        type: boolean
  
  # Common
  
  DoubleKnob:
    type: object
    required:
    - type
    - value
    properties:
      type:
        enum: ["Swift.Double"]
      value:
        type: number
  
  Int32Knob:
    type: object
    required:
    - type
    - value
    properties:
      type:
        enum: ["Swift.Int32"]
      value:
        type: integer
        format: int32
  
  Int64Knob:
    type: object
    required:
    - type
    - value
    properties:
      type:
        enum: ["Swift.Int64"]
      value:
        type: integer
        format: int64

  StringKnob:
    type: object
    required:
    - type
    - value
    properties:
      type:
        enum: ["Swift.String"]
      value:
        type: number  
  
  ExecutionMode:
    type: object
    required:
    - type
    - value   
    properties:
      type:
        enum: ["FAST.ExecutionMode"]
      value:
        enum: ["Default", "Emulated"]

  ResourceUsagePolicy:
    type: object
    required:
    - type
    - value
    properties:
      type:
        enum: ["FAST.ResourceUsagePolicy"]
      value:
        enum: ["Simple", "Maintain", "Maximal"]
        
  ActuationPolicy:
    type: object
    required:
    - type
    - value
    properties:
      type:
        enum: ["FAST.ActuationPolicy"]
      value:
        enum: ["Actuate", "NoActuation"]
        
  InteractionMode:
    type: object
    required:
    - type
    - value
    properties:
      type:
        enum: ["FAST.InteractionMode"]
      value:
        enum: ["Default", "Scripted"]
        
  Cores:
    type: object
    required:
    - type
    - value
    properties:
      type:
        enum: ["Swift.Int"]
      value:
        enum: [1,2,3,4]  
  
  # Xlilinx ZCU
  
  XilinxCoreFrequency:
    type: object
    required:
    - type
    - value
    properties:
      type:
        enum: ["Swift.Int"]
      value:
        enum:
          [300, 400, 600, 1200]
  
  # ODROID
  
  OdroidLittleCoreFrequency:
    type: object
    required:
    - type
    - value
    properties:
      type:
        enum: ["Swift.Int"]
      value:
        enum:
          [ 200000, 300000, 400000, 500000
          , 600000, 700000, 800000, 900000
          , 1000000, 1100000, 1200000, 1300000
          , 1400000
          ]

  OdroidBigCoreFrequency:
    type: object
    required:
      - type
      - value
    properties:
      type:
        enum: ["Swift.Int"]
      value:
        enum:
          [ 200000, 300000, 400000, 500000
          , 600000, 700000, 800000, 900000
          , 1000000, 1100000, 1200000, 1300000
          , 1400000, 1500000, 1600000, 1700000
          , 1800000, 1900000, 2000000
          ]

  OdroidUtilizedSystemConfiguration:
    type: object
    required:
    - utilizedLittleCores
    - utilizedLittleCoreFrequency
    - utilizedBigCores
    - utilizedBigCoreFrequency
    properties:
      utilizedLittleCores:
        $ref: '#/definitions/Cores'
      utilizedLittleCoreFrequency:
        $ref: '#/definitions/OdroidLittleCoreFrequency'
      utilizedBigCores:
        $ref: '#/definitions/Cores'
      utilizedBigCoreFrequency:
        $ref: '#/definitions/OdroidBigCoreFrequency'

  OdroidAvailableSystemConfiguration:
    type: object
    required:
    - availableLittleCores
    - maximalLittleCoreFrequency
    - availableBigCores
    - maximalBigCoreFrequency
    properties:
      availableLittleCores:
        $ref: '#/definitions/Cores'
      maximalLittleCoreFrequency:
        $ref: '#/definitions/OdroidLittleCoreFrequency'
      availableBigCores:
        $ref: '#/definitions/Cores'
      maximalBigCoreFrequency:
        $ref: '#/definitions/OdroidBigCoreFrequency'
  
  OdroidArchitecture:
    type: object
    required:
    - energy
    - systemConfigurationKnobs
    - resourceUsagePolicyModule
    - scenarioKnobs
    - executionMode
    - actuationPolicy
    - time
    properties:
      energy:
        type: integer
        format: int64
        minimum: 0
      systemConfigurationKnobs:
        $ref: '#/definitions/OdroidUtilizedSystemConfiguration'
      resourceUsagePolicyModule:
        type: object
        required:
        - maintainedState
        - policy
        properties:
          maintainedState:
            $ref: '#/definitions/OdroidUtilizedSystemConfiguration'
          policy:
            $ref: '#/definitions/ResourceUsagePolicy'
      scenarioKnobs:
        schema:
          $ref: '#/definitions/OdroidAvailableSystemConfiguration'
      executionMode:
        $ref: '#/definitions/ExecutionMode'
      actuationPolicy:
        $ref: '#/definitions/ActuationPolicy'
      time:
        type: number
        minimum: 0
  
  KeyNumberPair:
    type: object
    description: "Data representing the value of a knob or measure."
    required:
      - key
      - value
    properties:
      key:
        type: string
      value:
        type: number

  # Identical to the response type of TH/status
  Status:
    type: object
    description: "Data representing the current state of the SUT."
    required:
      - time
      - arguments
    properties:
      time:
        type: string
        description: "UTC Time in RFC-3339 format."

      arguments:
        type: object
        description: "The challenge application state, the system state, the scenario knobs, and the verdict components."
        required:
          - application
          - applicationKnobs
          - architecture
          - systemConfigurationKnobs
          - scenarioKnobs
          - runningTime
          - energy
          - numberOfProcessedInputs
          - measures
        properties:
          application:
            enum: ["radar", "x264", "CaPSuLe"]
            description: "Name of challenge problem application."
          applicationKnobs:
            type: array
            description: "Application-dependent listing the value of each application knob."
            items:
              $ref: '#/definitions/KeyNumberPair'
          architecture:
            type: string
            description: "Name of the system architecture."  
          systemConfigurationKnobs:
            type: array
            description: "Architecture dependent listing the value of each system configuration knob."
            items:
              $ref: '#/definitions/KeyNumberPair'
          scenarioKnobs:
            type: array
            description: "Architecture dependent settings describing the current available system resources such as the number of cores and maximal operation frequency."
            items:
              $ref: '#/definitions/KeyNumberPair'
          runningTime:
            type: number
            description: "Application running time."
          energy:
            type: number
            minimum: 0
            description: "Energy consumed (in microjoules)."
          numberOfProcessedInputs:
            type: integer
            minimum: 0
            description: "Number of inputs (from the current input stream) that have been processed."
          measures:
            type: array
            description: "Values of measures specified in the intent specification."
            items:
              $ref: '#/definitions/KeyNumberPair'